common:
  dirmodel: model_test
  dirapply: validation_test
  dirplots: plots_test
  dirtree: /mnt/temp/mkabus/test
  dirhist: /mnt/temp/mkabus/test
  #dirinput_bias: /data/tpcml/data_20200518/bias
  #dirinput_nobias: /data/tpcml/data_20200518/nobias
  dirinput_bias: /mnt/temp/dsekihat/data/tpcml/data_20210414/noDistortions
  dirinput_nobias: /mnt/temp/dsekihat/data/tpcml/data_20210414/noDistortions
  train_bias: true
  validation_bias: true
  apply_bias: false
  nd_val_events: 1000 # Number of events for validation (random events for nd_validation)
  nd_val_partition: random # Whether the validator uses only the events from given partition
                           # 'random' is for choosing events randomly
  nd_validate_model: true
  pdf_map_var: flucSC
  pdf_map_mean_id: 0
  grid_phi: 180
  grid_z: 33
  grid_r: 33
  z_range: [0, 251] # train for distortions with min <= z < max
  opt_train: [1, 1] # first position = meanSC, second = SCfluctuations
  opt_predout: [1, 0, 0] # R, Rphi, z output distortion predictions
  nameopt_predout: [R, RPhi, Z] # R, RPhi, Z output distortion predictions
  maxrandomfiles: 1000 # this is the total number of random events generated
  range_rnd_index_train: [0, 999] # min and max index of random SC configurations for training
  range_rnd_index_nd_val: [0, 999] # min and max index of random SC configurations for nd validation
  range_mean_index: [0, 44] # min and max index of mean SC configurations
  rnd_augment: false # use rnd-rnd augmentation instead of rnd-mean. Only used for model training
  num_fourier_coeffs_train: 40 # number of Fourier coefficients to take from the 1D IDC train input
  num_fourier_coeffs_apply: 40 # number of Fourier coefficients to take from the 1D IDC apply input

xgboost:
  active: True
  train_events: [200]
  validation_events: [100]
  apply_events: [400]
  downsample: true
  downsample_npoints: 100
  plot_train: false
  train_plot_npoints: 10
  params:
    n_estimators: 100 # 850, 100 is better than 500
    max_depth: 3
    learning_rate: 1 # 1 is better than 0.1 and 3.0
    objective: "reg:squarederror"
    booster: "gbtree"
    tree_method: "hist"
    n_gpus: 0
    n_jobs: 10
    gamma: 0
    min_child_weight: 1 #3
    max_delta_step: 0
    subsample: 0.8
    colsample_bytree: 1 #0.8
    colsample_bylevel: 1
    colsample_bynode: 0.8
    reg_alpha: 0
    reg_lambda: 0.00005
    scale_pos_weight: 1
    base_score: 0.5

corr:
  active: false

dnn:
  active: false
  train_events: [5000] # 5000, 18000
  validation_events: [600] # 500, 1800
  apply_events: [1400] # 7000, 7000
  use_scaler: false
  filters: 4
  pool_type: "max" # max, avg, conv
  depth: 4
  batch_normalization: false
  dropout: 0.0
  batch_size: 27
  shuffle: false
  epochs: 20
  lossfun: mse
  metrics: mse
  adamlr: 0.001000
