case: DNN_fluctuations
dotrain: false
doapply: true
doplot: true
dogrid: false
doprofile: true
docreatevaldata: false
docreatepdfmaps: false
docreatepdfmapforvariable: false
docreatepdfmapformeanid: false
domergepdfmaps: false
