dotrain: true
doapply: true
doplot: true
dogrid: false
dobayes: false
doprofile: false
docreatendvaldata: true
docreatepdfmaps: true
docreatepdfmapforvariable: true
docreatepdfmapformeanid: true
domergepdfmaps: true
